fix(user): Add required fields and mixins
[Problem]
Error logging into Django admin site.
Custom user auth model lacks platform dependent fields and methods.

[Error]
```
Type:	AttributeError
Value:  'User' object has no attribute 'is_staff'

Type:	AttributeError
Value:	'User' object has no attribute 'has_module_perms'
```

[Fix]
Update custom user model to define fields required by Django apps.