fix(tox): Enable tox to manage `django` versions
[Problem]
Django dependency resolutions occur in CI during tox installation step.

[Error]
```
django50: install_deps> python -I -m pip install 'Django<5.1,>=5.0' -r /home/runner/work/Agizo/Agizo/requirements/test-ci.txt
ERROR: Cannot install Django<5.1 and >=5.0 and django==4.2.18 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested Django<5.1 and >=5.0
    The user requested django==4.2.18
```

[Fix]
Remove Django pkg from test-ci.txt to avoid conflicts with tox
specified Django version.

[Note]
- Add bash script to remove Django from test-ci.txt then run
  default tox install command.
- Update test-ci.in to pull both base and test deps (ignore hack)